### ISSUE TITLE
[Suggestion] Route smart auto-loading

### ISSUE THREAD

**Issue by ghost** [ideka/AugTyr#17]
I'm not exactly sure as to why you removed route automatically loading but I can guess it's because it breaks unified routes (eg when doing hoelbrak/rata sum and you need to enter an instance).

My suggestion here is to have a Blacklist or whitelist of sorts that checks if the current map is "allowed" to load or not. 

I think a 'for loop' that gets the names of current routes in the routes folder and adds them to a whitelist would be the simpler solution for now.

Disclaimer: I have no idea how map ID's change when entering an instance in a city

**Comment by ideka** [comment]
> I'm not exactly sure as to why you removed route automatically loading but I can guess it's because it breaks unified routes (eg when doing hoelbrak/rata sum and you need to enter an instance).

That is correct.

I'll think of some options for smart auto-loading for v0.3 (actually I might push that to v0.4, as v0.3 is already taking too long).

**Comment by ideka** [comment]
Done as of c0a0027c1be8412175f87aa322c9fba5b7637501.
