### ISSUE TITLE
How can i finish update？and i have some problem......

### ISSUE THREAD

**Issue by Holdor1** [ideka/AugTyr#19]
if  you have something about update for AugTyr.  Do I need to download AugTyr 0.3 again？ehh，because 
The map of the Dredgehaunt cliff, the route is in the sky or underground, is not a normal route, but I didn't have this situation when I ran other pictures, why?

**Comment by Holdor1** [comment]
Your Provided routes have Dredgehaunt cliff, so i think  mybe  have some update for this . If it is not , i do hope you can    help . thanks very much!!!!

**Comment by ideka** [comment]
Press Numpad / to load the right route.

**Comment by Holdor1** [comment]
sorry，i know this instruction  and I also use it correctly on other maps , but only Dredgehaunt cliff  doesn't respond to this instruction .Sometimes there is no route, or the route is wrong , how to  solve?

**Comment by Holdor1** [comment]
![3fb6d3fdfc039245ac769cf48794a4c27f1e2586](https://user-images.githubusercontent.com/30768739/29052093-3a70867c-7c1a-11e7-83b9-d980337bc8bc.jpg)

**Comment by ideka** [comment]
I see. The route had broken json. Not sure how it happened, but I was able to restore it I think (f334336eca95a4065f9096faee9eb5df363892e8).

[Get the fixed route here.](https://github.com/ideka/AugTyr/blob/f334336eca95a4065f9096faee9eb5df363892e8/Assets/StreamingAssets/UnofficialRoutes/26.json)

**Comment by Holdor1** [comment]
How will I use the code you gave me? Is the original code completely replaced?

**Comment by ideka** [comment]
Download [this](https://raw.githubusercontent.com/ideka/AugTyr/f334336eca95a4065f9096faee9eb5df363892e8/Assets/StreamingAssets/UnofficialRoutes/26.json) file, put it in `AugTyr_Data/StreamingAssets/UnofficialRoutes/` replacing the old one.

**Comment by Holdor1** [comment]
Thank you very much. The problem has been solved.
I hope you can make more map routes in the future, and I will strongly support you! 
![image](https://user-images.githubusercontent.com/30768739/29053300-e224011c-7c21-11e7-9f1c-31a45181e7fc.png)
