### ISSUE TITLE
Updates ?

### ISSUE THREAD

**Issue by TicWE** [ideka/AugTyr#2]
Are there any updates ? Or new routes from the community ?

**Comment by Tenelia** [comment]
Second this. Will you build a v0.2? I see you making quite a few changes.

**Comment by TicWE** [comment]
Well I'm just asking because I don't own this and didn't build it. But would be cool if those who created new routes shared them here for example ^^

**Comment by ideka** [comment]
Honestly, I kinda want to jump straight to a v1.0 beta. But I'll have to complete all central Tyria routes first.

**Comment by Tenelia** [comment]
I think the content will come if you put out an update. (: I could do one route, if it's only just marking out the spots?

**Comment by ideka** [comment]
I don't know about that :P.

I could release an update but then I'd also have to explain a bunch of stuff, put out a tutorial that nobody will read, etc. And then I'll have to do it *again* to explain all the changes when I put out the final version.

For now if you want the current version early, just get Unity 5.6.2 (free version will do I think) and build it yourself. It's not hard.

And last but not least, route making instructions and official route making policy can both be found [here](https://www.reddit.com/r/AugmentedTyria/comments/5yvnfo/route_making_progress/).

**Comment by TicWE** [comment]
Mmmh and what about changing the color of the first node ?

**Comment by Ryaden** [comment]
It's pretty easy to add your own routes, fork it, add your *.json files which you've created ingame and make a pull request for ideka.

**Comment by ideka** [comment]
@TicWE Are you requesting that as a change? Asking how to do it?

**Comment by TicWE** [comment]
I wouldn't be able to do it myself ^^
Btw do I need a .json.meta with every route ? (I don't know what these files are)

**Comment by ideka** [comment]
I don't think having the first node be a different color will be necessary. In the future, other things will help you determine the beginning of a route.

> Btw do I need a .json.meta with every route ? (I don't know what these files are)

These are just Unity-related stuff. The built tool works fine with or without them.

**Comment by TicWE** [comment]
Any ideas to bring more people here to get more maps quickly ? Would be pretty nice

**Comment by Tenelia** [comment]
I think most people are actually hoping for routes on Tangled Depths (based on my chat with guildies and random map meta squads). It's not too hard to complete the main maps.

**Comment by ideka** [comment]
> I think most people are actually hoping for routes on Tangled Depths (based on my chat with guildies and random map meta squads). It's not too hard to complete the main maps.

That...seems to pop up a lot, yes. It's not a priority for me right now (plus I'm not really a route-maker per se, so far I've just been converting Lulle's routes), but I will probably make one in the future if nobody beats me to it (and if someone does make one before v0.3, expect it to be included as an "unofficial route," as the unofficial route system is the last big feature I want to implement for v0.3).

**Comment by TicWE** [comment]
Yeah but we should attract more people who could become route makers maybe ? (And how?)

**Comment by Tenelia** [comment]
I've been trying to plonk down markers for the Tangled Depths route, but I might say that it's HARD...

**Comment by ideka** [comment]
An unofficial [route for Tangled Depths](https://github.com/ideka/AugTyr/blob/fc21ba9b608ac538d3aa1cc425dd61a1b5308139/Assets/StreamingAssets/UnofficialRoutes/1045.json) has been contributed and, I've pushed it to the repository (haven't tested it though, hence unofficial).

It'll be bundled with the next official release, or you can get it early from the link above.

Anyway, this issue was originally about updates, which there has been, so I'm closing it now.
