### ISSUE TITLE
Farming routes

### ISSUE THREAD

**Issue by TicWE** [ideka/AugTyr#21]
I was thinking of being able to have multiple routes for one map, for example a farming route, an exploration one etc, with the possibility to switch between them. A farming route that would cover several maps could be great too though ^^

**Comment by TicWE** [comment]
I was thinking of a new mode that would be exactly the same thing as the follow mode but would load farming routes instead of exploration routes

**Comment by TicWE** [comment]
I am currently trying to do the farming routes, but can I get a first like two routes on the same map without them being attached to each other ?

**Comment by TicWE** [comment]
I can do the whole route on a single map file, but I need an ID that won't interact with any map, such as Heart of the Mists for example, could you help me ? I'm scared it would be too messy unless follow mode is used

**Comment by TicWE** [comment]
Up ??

**Comment by ideka** [comment]
> I was thinking of being able to have multiple routes for one map, for example a farming route, an exploration one etc, with the possibility to switch between them.

Such a feature has been on my mind for a long time, but I have no plans for it.

> A farming route that would cover several maps could be great too though ^^

Too difficult to implement, not to say impossible. Map coordinates aren't consistent with each other.

> I can do the whole route on a single map file, but I need an ID that won't interact with any map, such as Heart of the Mists for example, could you help me ?

There is no map in the game with an ID of 0, and there'll probably never be. I guess you can try a negative ID too. Not sure if it'd work.

**Comment by TicWE** [comment]
Yeah but with a negative ID, how would I load the route ?

**Comment by ideka** [comment]
Copy for example, "-3" to your clipboard. Then hit Ctrl + Numpad /.

Not sure if it'd work, as I said. But ID 0 should, same method.

**Comment by TicWE** [comment]
So I load the ID 0 map with Ctrl + Numpad / and then starts making the route ?

**Comment by ideka** [comment]
Copy the number 0 to your clipboard then use Ctrl + Numpad /. This loads the route with an ID of 0. Make the route normally, saving with Numpad * and all that.

You can load the route back later the same way. Copy the number 0, then use Ctrl + Numpad /.

**Comment by Superritchman** [comment]
> A farming route that would cover several maps could be great too though

How about splitting the farmingroute into seperate routes per map.
You can end a route with a waypoint label and if you travel to the new map, it will autoload part two of the route.

**Comment by TicWE** [comment]
How would this autoload the new route from the map ?
Because when I change map the command says "Map change detected, please load... "

**Comment by TicWE** [comment]
Can I put some text on any node or only on some specific ones ? I've only been able to write on WP nodes

**Comment by TicWE** [comment]
I've almost finished the one I was working on, it's covering permanent nodes for several ressources, and covers a lot of maps. I've chosen the ID 0 but we'll need map dedicated farming routes too ;)

**Comment by ideka** [comment]
> How would this autoload the new route from the map ?

A route with an ID of 0 will never be autloaded with current autoloading rules.

> Can I put some text on any node or only on some specific ones ? I've only been able to write on WP nodes

Any node can have text. Check the readme.

**Comment by TicWE** [comment]
Well Ctrl + Numpad 3 only works on cyan nodes

**Comment by ideka** [comment]
> Well Ctrl + Numpad 3 only works on cyan nodes

I shouldn't need to explain stuff personally when it's already explained in the readme: check the readme.

**Comment by TicWE** [comment]
All right found out how to do it

**Comment by TicWE** [comment]
I've finished my prototype of this farming route, where do I upload it ?

**Comment by ideka** [comment]
Anywhere, I'll put it in the repository.

**Comment by TicWE** [comment]
[0.txt](https://github.com/ideka/AugTyr/files/1269816/0.txt)

**Comment by ideka** [comment]
I've added the route to the repository.
