### ISSUE TITLE
Follow mode expects too much precision movement and jumping. 

### ISSUE THREAD

**Issue by wolfeng-db** [ideka/AugTyr#22]
From what I understand, the follow mode is when you have a green arrow pointing you to another node,  those disappear when you get close to them and it even auto copies waypoints, while the editor mode shows everything all the time even through walls and mountains. 

Anyway, the follow modes expects the movement too much be the exact same, walk a few cm to the side of the purple ball and it doesn't register, jump further ahead than expected and it doesn't register. 

This creates a situation where you either have to go back and "trigger it" or keep pressing 6 to move the route along with you. 

Would it be possible to have this feature be more lenient with our movement? Maybe increase the range of detection? Maybe autoupdate the route if we are going ahead of a series of nodes?

**Comment by ghost** [comment]
I do agree with this. A possible solution would be to have an area behind/to the sides of the character which acts as a node consumer.

i.e rather than a circle centered on the character have a square centered behind the character with the radius being equal to the distance away from the center point.

This makes it such that you do not prematurely consume nodes but if you run past but the node still hit invisible box it still gets consumed

**Comment by ideka** [comment]
I'll probably do something about it.

**Comment by gbdematos** [comment]
This is really relevant specially now with mounts, as it's more difficult to touch the little nodes.

Would increasing its size solve it, maybe?

Edit: just saw the NodeSize config and undestood it has nothing to do with the area of contact.

**Comment by ideka** [comment]
I still plan on addressing this, it'll just have to wait a bit as I'm quite busy these days.

**Comment by json-m** [comment]
a little late to the party, but there is a variable exposed in the code that helps with this if you are up to building it yourself in unity.

https://github.com/ideka/AugTyr/blob/c52be16df4b85a8758d77efa5a0a459016844524/Assets/Augmented%20Tyria/Scripts/Follow%20Mode/FollowMode.cs#L18

example (value set to 100): https://gfycat.com/NiftyTerribleAustralianfurseal

**Comment by ideka** [comment]
Oh, this is fixed as of v0.5.
